### ISSUE TITLE
Mismatch between cloud id and flag state

### ISSUE THREAD

**Issue by Ned-Flanders** [HarukaMa/starfield-xgp-import#7]
I keep getting this error, both using the exe and python, I have python 11 installed.

![erroir](https://github.com/HarukaMa/starfield-xgp-import/assets/6885462/af363019-365a-483b-bec6-c8613463cb6e)

**Comment by HarukaMa** [comment]
did you just exit the game? you might need to wait for a while as the xbox app might still be syncing the save data if the container is in this state.

**Comment by Ned-Flanders** [comment]
I exited about half an hour ago but I'm still getting the same error unfortunately

**Comment by HarukaMa** [comment]
Then I can't safely modify that container because the only case I've seen that is when the game has just exited and (presumably) the save file is still being synced to the cloud. I'm curious about the actual values though, should have printed them in the error messages.

Maybe try changing the existing save files by overwriting / modifying them to force another sync. Or as the last resort, remove that check in code.

**Comment by Ned-Flanders** [comment]
Hey man, I managed to get rid of the error, I booted up Starfield, it updated then prompted me to sync my cloud saves, I tried to convert the save again and it worked, looked like that was the issue. Thanks for your help and the program, it's great.
